### PR TITLE
Extended fort defence

### PR DESCRIPTION
**Pull request by valdisz**
I have implemented an extended fort (all fortifications) defense feature.

This feature extends fort defense bonus on garrisons joining battles in adjacent regions. Bonus will be applied only if garrison is defending, i.e. treat this as a siege on the fort.

### CODE REVIEW

**Comment by valdisz** [comment]
I had recently thought about this feature and came to the conclusion that building "a wall" of forts will make problems. This is a powerful thing.

I had an idea to limit the building of forts so that there must be no fort in the 2 hex radius. Also, it would be nice to limit the number of defense structures to 1 per hex with `BUILD UPGRADE` command to upgrade smaller fort into bigger.

That would need to increase fort sizes too.

What do others think about this? I can implement all that is listed here.

**Comment by arkadybabaev** [comment]
build upgrade is a perfect thing.
problem with "a wall" I think doesn't exist. To have wall of 7 hexes you have to split your army to 3 equal parts. It's not efficient while "wall" doesn't triples army's value.

But to add to your taxers and other meat a value of being able at least to stop the entering army for a turn, the "wall" would work perfectly, and strategically first time in Atlantis it will be profitable to build fortresses for exact reason for which they were designed: to slow down enemy.

**Comment by arkadybabaev** [comment]
there is another flag related to fortress: ADVANCED_FORTS
Was it taken into consideration?

**Comment by valdisz** [comment]
The one for changing hit chance? It will work together, but how balanced it will be I cannot predict. One is clear: you can tur on both :)

**Comment by artyomtrityak** [comment]
Unfortunately i do not see this PR moving forward. Please reopen if something changes.

**Comment by valdisz** [comment]
@artyomtrityak I have added a check for ships/fleets. No bonus will be added when "garrison" is in the fleet. I think I can be merged into `master` branch.

**Pull request closed without merging**
