### PR TITLE
Clarify food consumption rules

### PR DESCRIPTION
**Pull request by sparr**

### CODE REVIEW

**Comment by sgb** [comment]
I think your English is fine, but you might want to bracket part of that addition in a check to see if the current UPKEEP_FOOD_VALUE and MAINTENANCE_COST settings actually make this a possibility?

Then you could phrase the "might" more strongly as appropriate.

**Comment by artyomtrityak** [comment]
@sgb do you mean we need to check there that `UPKEEP_FOOD_VALUE  > MAINTENANCE_COST` ?

**Comment by sgb** [comment]
Probably whether they're co-prime actually :-)

**Comment by sgb** [comment]
MAINTENANCE_COST % UPKEEP_FOOD_VALUE != 0

Because while a maintenance cost of 10 and a food value of 30 can leave leftovers, so can a maintenance cost of 10 and a food value of 6.

**Comment by sparr** [comment]
You'd also need to check LEADER_COST, and the ability to mix leaders and races in the same unit.

**Comment by sgb** [comment]
Good point about LEADER_COST, but whether you can combine them doesn't matter

**Comment by artyomtrityak** [comment]
@sparr are you going to continue work on this PR or it can be closed?

**Comment by sparr** [comment]
@artyomtrityak what other changes do you want? I think I addressed most of the feedback here and on slack in my latest commit.

**Pull request closed without merging**
